server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://nbfhgucjnqvtbq:9946cb089d679e6d10439934ebad94f18f39b51c0b6e11b3df6f93c44050e7b3@ec2-34-193-112-164.compute-1.amazonaws.com:5432/d6kh6m38j7itbm
    username: nbfhgucjnqvtbq
    password: 9946cb089d679e6d10439934ebad94f18f39b51c0b6e11b3df6f93c44050e7b3
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander
